name: epi293
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.45
  - boost-cpp=1.74.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - curl=8.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran_impl_linux-64=15.2.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - harfbuzz=6.0.0
  - icu=70.1
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.20.1
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgit2=1.7.1
  - libglib=2.78.1
  - libgomp=15.2.0
  - libhwloc=2.9.1
  - libiconv=1.18
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libsanitizer=15.2.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - make=4.4.1
  - mkl=2024.2.2
  - ncurses=6.5
  - openssl=3.6.0
  - pandoc=3.8.3
  - pango=1.50.14
  - pcre2=10.40
  - pixman=0.46.4
  - plink=1.90b7.7
  - plink2=2.0.0a.6.9
  - pthread-stubs=0.4
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-base=4.2.3
  - r-base64enc=0.1_3
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-commonmark=1.9.1
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.1
  - r-curl=5.0.1
  - r-data.table=1.15.4
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diffobj=0.3.5
  - r-digest=0.6.36
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-ellipsis=0.3.2
  - r-evaluate=0.24.0
  - r-expm=0.999_9
  - r-fansi=1.0.6
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-fs=1.6.4
  - r-generics=0.1.3
  - r-gert=2.0.1
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-glue=1.7.0
  - r-highr=0.11
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=0.2.3
  - r-ini=0.3.1
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-knitr=1.47
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-mvtnorm=1.2_5
  - r-openssl=2.2.0
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.0.9
  - r-pkgload=1.3.4
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-profvis=0.3.8
  - r-promises=1.3.0
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcpp=1.0.12
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-rlang=1.1.4
  - r-rmarkdown=2.27
  - r-roxygen2=7.3.2
  - r-rprojroot=2.0.4
  - r-rstudioapi=0.16.0
  - r-rversions=2.1.2
  - r-sass=0.4.9
  - r-sessioninfo=1.2.2
  - r-shiny=1.8.1.1
  - r-sourcetools=0.1.7_1
  - r-stringi=1.7.12
  - r-stringr=1.5.1
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-testthat=3.2.1.1
  - r-textshaping=0.3.6
  - r-tibble=3.2.1
  - r-tidyselect=1.2.1
  - r-tinytex=0.51
  - r-urlchecker=1.0.1
  - r-usethis=2.2.3
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-waldo=0.5.2
  - r-whisker=0.4.1
  - r-withr=3.0.0
  - r-xfun=0.45
  - r-xml2=1.3.3
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.8
  - r-zip=2.3.1
  - readline=8.3
  - regenie=4.1.2
  - sed=4.9
  - sqlite=3.51.1
  - sysroot_linux-64=2.28
  - tbb=2021.9.0
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2025c
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7